name: automatic-photometric-qa
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dask
  - distributed
  - dask-jobqueue
  - ipykernel
  - ipython
  - lsdb
  - matplotlib
  - nbclient
  - nbconvert
  - nbformat
  - numpy
  - pandas
  - pyarrow
  - psycopg
  - pyyaml
  - seaborn
